spring:
  application:
    name: task-manager-api
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: postgres
    password: 1234pass
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080